[tool.poetry]
name = "concatenative"
version = "0.1.0"
description = ""
authors = ["daddinuz <daddinuz@gmail.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
